app:
  name: movie-recommender
  version: 1.0.0
  debug: false

server:
  host: 0.0.0.0
  port: 5000

artifacts_path: artifacts/

logging:
  level: INFO
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
